brew install --cask anaconda
brew install --cask angry-ip-scanner
brew install --cask anydesk
brew install --cask asana
brew install --cask autodesk-fusion
brew install --cask blender
brew install --cask bluestacks
brew install --cask chatgpt
brew install --cask cloudcompare
brew install --cask creality-slicer
brew install --cask cura
brew install --cask discord
brew install --cask docker
brew install --cask epic-games
brew install --cask google-chrome
brew install --cask grammarly
brew install --cask logitech-options
brew install --cask mattermost
brew install --cask microsoft-excel
brew install --cask microsoft-powerpoint
brew install --cask microsoft-word
brew install --cask miniconda
brew install --cask notion
brew install --cask pycharm
brew install --cask raspberry-pi-imager
brew install --cask slack
brew install --cask steam
brew install --cask telegram
brew install --cask visual-studio-code
brew install --cask vmware-fusion
brew install --cask vnc-viewer
brew install --cask webex
brew install --cask whatsapp
brew install --cask zed
brew install --cask zoom
brew install --cask zotero

brew autoremove
brew cleanup
