brew install cask google-chrome
brew install cask visual-studio-code
brew install cask vnc-viewer
brew install cask slack
brew install cask zoom
brew install cask docker
brew install cask vmware-fusion
brew install cask zotero
brew install cask discord
brew install cask cloudcompare
brew install cask telegram
brew install cask whatsapp
brew install cask webex
brew install cask mattermost
brew install cask autodesk-fusion
brew install cask logitech-options
brew install cask anydesk
brew install cask angry-ip-scanner
brew install cask raspberry-pi-imager
